
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
// Nếu dùng DBContext ở package khác thì import nó vào đây, ví dụ:
// import helper.DBContext;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class KiemKeFrame extends javax.swing.JFrame {

    public void loadDataKiemKe() {
        DefaultTableModel model = (DefaultTableModel) tblKiemKe.getModel();
        model.setRowCount(0); // Xóa bảng cũ
        try {
            Connection conn = new DBContext().getConnection();
            // 1. Lấy thêm cột loaiNVL để hiển thị cho đủ giao diện
            String sql = "SELECT maNVL, tenNVL, loaiNVL, soLuong FROM NGUYEN_VAT_LIEU";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                // 2. Thêm đúng 6 cột như trên giao diện xanh của Đạt
                model.addRow(new Object[]{
                    rs.getString("maNVL"), // Cột 0
                    rs.getString("tenNVL"), // Cột 1
                    rs.getString("loaiNVL"), // Cột 2
                    rs.getInt("soLuong"), // Cột 3: Số lượng trên máy
                    "", // Cột 4: Thực tế (để trống cho Đạt nhập)
                    "0" // Cột 5: Chênh lệch
                });
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form KiemKeFrame
     */
    public KiemKeFrame() {
        initComponents();
        setLocationRelativeTo(null); // Hiện giữa màn hình
        loadDataKiemKe();           // GỌI HÀM NÀY Ở ĐÂY THÌ BẢNG MỚI HIỆN CHỮ
        tblKiemKe.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
        @Override
        public void tableChanged(javax.swing.event.TableModelEvent e) {
            // Kiểm tra nếu Đạt sửa cột "Số lượng thực tế" (Cột số 4)
            if (e.getColumn() == 4) { 
                int row = e.getFirstRow();
                try {
                    // Lấy số lượng trên máy (Cột 3) và số thực tế Đạt nhập (Cột 4)
                    int trenMay = Integer.parseInt(tblKiemKe.getValueAt(row, 3).toString());
                    int thucTe = Integer.parseInt(tblKiemKe.getValueAt(row, 4).toString());

                    // Tính chênh lệch và hiển thị vào cột 5
                    int chenhLech = thucTe - trenMay;
                    tblKiemKe.setValueAt(chenhLech, row, 5);
                } catch (Exception ex) {
                    // Tránh lỗi khi nhập chữ hoặc để trống
                }
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKiemKe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnXacNhanKiemKe = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiểm kê");

        tblKiemKe.setBackground(new java.awt.Color(0, 255, 204));
        tblKiemKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaNVL", "TenNVL", "LoaiNVL", "Số lượng trên máy", "Số lượng thực tế", "Chênh lệch"
            }
        ));
        tblKiemKe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblKiemKePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblKiemKe);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("KIỂM KÊ");

        btnXacNhanKiemKe.setBackground(new java.awt.Color(204, 255, 204));
        btnXacNhanKiemKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXacNhanKiemKe.setText("Xác nhận kiểm kê");
        btnXacNhanKiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanKiemKeActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(316, 316, 316)
                        .addComponent(btnXacNhanKiemKe))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(489, 489, 489))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnXacNhanKiemKe)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnThoat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanKiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanKiemKeActionPerformed
 try {
    String maKK = "KK" + new java.text.SimpleDateFormat("ddMMss").format(new java.util.Date());
    Connection conn = new DBContext().getConnection();
    
    // --- BƯỚC 1: LƯU VÀO BẢNG CHÍNH ---
    String sqlPhieu = "INSERT INTO KIEM_KE (maKK, ngayKiemKe, nguoiKiemKe) VALUES (?, GETDATE(), ?)";
    PreparedStatement pstmtP = conn.prepareStatement(sqlPhieu);
    pstmtP.setString(1, maKK);
    pstmtP.setString(2, "NGUYỄN THÀNH ĐẠT"); 
    pstmtP.executeUpdate(); 

    // --- BƯỚC 2: CHẠY VÒNG LẶP LƯU CHI TIẾT (CÓ LƯU CHÊNH LỆCH) ---
    for (int i = 0; i < tblKiemKe.getRowCount(); i++) {
        String maNVL = tblKiemKe.getValueAt(i, 0).toString();
        int thucTe = Integer.parseInt(tblKiemKe.getValueAt(i, 4).toString());
        
        // Lấy con số chênh lệch từ cột số 5 trên bảng của Đạt
        int chenhLech = Integer.parseInt(tblKiemKe.getValueAt(i, 5).toString());

        // Cập nhật SQL: Thêm cột chenhLech vào đây
        String sqlCt = "INSERT INTO CHITIET_KIEM_KE (maKK, maNVL, soLuongThucTe, chenhLech) VALUES (?, ?, ?, ?)";
        PreparedStatement pstmtCt = conn.prepareStatement(sqlCt);
        pstmtCt.setString(1, maKK);
        pstmtCt.setString(2, maNVL);
        pstmtCt.setInt(3, thucTe);
        pstmtCt.setInt(4, chenhLech); // Nạp con số chênh lệch vào Database
        pstmtCt.executeUpdate();
    }
    
    // --- BƯỚC 3: HIỂN THỊ PHIẾU VÀ THÔNG BÁO ---
    PhieuKiemKeFrame phieu = new PhieuKiemKeFrame(); 
    phieu.displayPhieu(maKK); 
    phieu.setVisible(true);   
       
    conn.close();
    JOptionPane.showMessageDialog(this, "Thành công rồi Đạt ơi! Mã phiếu: " + maKK);

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    e.printStackTrace();
}                                              
       // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanKiemKeActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        // 1. Khởi tạo lại màn hình chính (MainFrame)
        // Lưu ý: Đạt kiểm tra chính xác tên Class của màn hình trong ảnh là gì nhé
        MainFrame main = new MainFrame();

        // 2. Hiển thị màn hình chính lên
        main.setVisible(true);
        main.setLocationRelativeTo(null); // Để nó hiện giữa màn hình

        // 3. Đóng (giải phóng) cửa sổ hiện tại (KiemKeframe)
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblKiemKePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblKiemKePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKiemKePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KiemKeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KiemKeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KiemKeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KiemKeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KiemKeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhanKiemKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKiemKe;
    // End of variables declaration//GEN-END:variables
}
