
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        btnQLNVL = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnNhacungcap = new javax.swing.JButton();
        btnQuanLyTonKho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        btnKiemKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"HỆ THỐNG QUẢN LÝ NGUYÊN VẬT LIỆU - ALMUS TECH\"");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("ALMUS TECH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnMain.setBackground(new java.awt.Color(204, 255, 255));

        btnQLNVL.setBackground(new java.awt.Color(153, 255, 255));
        btnQLNVL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQLNVL.setText("Nguyên vật liệu");
        btnQLNVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVLActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(51, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnNhacungcap.setBackground(new java.awt.Color(102, 255, 255));
        btnNhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhacungcap.setText("Nhà cung cấp");
        btnNhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhacungcapActionPerformed(evt);
            }
        });

        btnQuanLyTonKho.setBackground(new java.awt.Color(153, 255, 255));
        btnQuanLyTonKho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuanLyTonKho.setText("Quản lý Tồn kho");
        btnQuanLyTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTonKhoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Hình ảnh\\Cuộn phim\\thumb_1717722924_main1-Recovered.jpg")); // NOI18N

        btnThongKe.setBackground(new java.awt.Color(153, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnKiemKe.setBackground(new java.awt.Color(153, 255, 255));
        btnKiemKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKiemKe.setText("Kiểm Kê");
        btnKiemKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnDangXuat))
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLNVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuanLyTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKiemKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(btnQLNVL)
                        .addGap(68, 68, 68)
                        .addComponent(btnNhacungcap)
                        .addGap(73, 73, 73)
                        .addComponent(btnQuanLyTonKho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btnThongKe)
                        .addGap(56, 56, 56)
                        .addComponent(btnKiemKe)
                        .addGap(20, 20, 20))
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnDangXuat)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVLActionPerformed

        // 1. Khởi tạo cửa sổ Nguyên Vật Liệu
        VatLieuFrame nvl = new VatLieuFrame();

        // 2. Hiển thị nó lên
        nvl.setVisible(true);

        // 3. Ẩn trang chủ đi (nếu bạn muốn)
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNVLActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed

        int check = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?");
        if (check == javax.swing.JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true); // Mở lại trang Login
            this.dispose(); // Đóng trang chủ
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnNhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhacungcapActionPerformed

        NhaCungCapFrame ncc = new NhaCungCapFrame();
        ncc.setVisible(true); // Mở trang Nhà cung cấp
        this.dispose();        // Đóng trang chủ
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhacungcapActionPerformed

    private void btnQuanLyTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTonKhoActionPerformed
        // 1. Khởi tạo cửa sổ Nguyên Vật Liệu
        TonKhoFrame qltk = new TonKhoFrame();

        // 2. Hiển thị nó lên
        qltk.setVisible(true);

        // 3. Ẩn trang chủ đi (nếu bạn muốn)
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyTonKhoActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed

       ThongKeFrame tk = new ThongKeFrame();

        // 2. Hiển thị nó lên
        tk.setVisible(true);

        // 3. Ẩn trang chủ đi (nếu bạn muốn)
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnKiemKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemKeActionPerformed
        KiemKeFrame kk = new KiemKeFrame();

        // 2. Hiển thị nó lên
        kk.setVisible(true);

        // 3. Ẩn trang chủ đi (nếu bạn muốn)
        this.dispose();  
// TODO add your handling code here:
    }//GEN-LAST:event_btnKiemKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnKiemKe;
    private javax.swing.JButton btnNhacungcap;
    private javax.swing.JButton btnQLNVL;
    private javax.swing.JButton btnQuanLyTonKho;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
