
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import java.awt.Image;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class NhaCungCapFrame extends javax.swing.JFrame {

    public void loadData() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableNCC.getModel();
            model.setRowCount(0);
            DBContext db = new DBContext();
            Connection conn = db.getConnection();
            String sql = "SELECT * FROM NHA_CUNG_CAP";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        /**
         * Creates new form NhaCungCapFrame
         */
    }

    public NhaCungCapFrame() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNCC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        cbLoaiHang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NHÀ CUNG CẤP");

        jTableNCC.setBackground(new java.awt.Color(204, 204, 255));
        jTableNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "maNCC", "tenNCC", "diaChi", "soDT", "loaiHang"
            }
        ));
        jTableNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNCC);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnThem.setBackground(new java.awt.Color(255, 204, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 204, 204));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 204, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("maNCC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("tenNCC");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("diaChi");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("soDT");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("loaiHang");

        txtMaNCC.setBackground(new java.awt.Color(255, 204, 204));
        txtMaNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSDT.setBackground(new java.awt.Color(255, 204, 204));
        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDiaChi.setBackground(new java.awt.Color(255, 204, 204));
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTenNCC.setBackground(new java.awt.Color(255, 204, 204));
        txtTenNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNCCActionPerformed(evt);
            }
        });

        cbLoaiHang.setBackground(new java.awt.Color(255, 204, 204));
        cbLoaiHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhựa (vỏ tai nghe)", "Cao su – silicon", "Pin", "vải , lưới", "mút, bọt biển", "Cổng sạc", "Chip Bluetooth", "keo, chất kết dính", "Nam châm", "Màng loa", "Khung kim loại", "Mạch, IC", "Vật liệu đóng gói", "Bao bì", "Dây điện", "Cáp kết nối" }));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem)
                            .addComponent(btnThoat))))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLoaiHang, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(66, 66, 66)
                .addComponent(btnXoa)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(jLabel1)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThoat)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cbLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(66, Short.MAX_VALUE))))))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(487, 487, 487))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNCCActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // 1. KIỂM TRA TRỐNG (Phải đưa lên đầu tiên)
            String ma = txtMaNCC.getText().trim();
            if (ma.equals("")) {
                JOptionPane.showMessageDialog(this, "Mã không được để trống!");
                txtMaNCC.requestFocus();
                return; // Dừng lại luôn, không chạy code bên dưới nữa
            }

            // 2. KẾT NỐI VÀ THÊM VÀO DATABASE
            DBContext db = new DBContext();
            Connection conn = db.getConnection();
            String sql = "INSERT INTO NHA_CUNG_CAP VALUES (?, ?, ?, ?, ?)";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, ma);
            st.setString(2, txtTenNCC.getText());
            st.setString(3, txtDiaChi.getText());
            st.setString(4, txtSDT.getText());
            st.setString(5, cbLoaiHang.getSelectedItem().toString());

            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");

            // 3. CẬP NHẬT LẠI BẢNG
            loadData();

            // 4. XÓA TRẮNG CÁC Ô NHẬP (Để nhập người mới)
            txtMaNCC.setText("");
            txtTenNCC.setText("");
            txtDiaChi.setText("");
            txtSDT.setText("");
            cbLoaiHang.setSelectedIndex(0);
            txtMaNCC.requestFocus(); // Đưa con trỏ về ô Mã

            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            String ma = txtMaNCC.getText(); // Lấy mã từ ô nhập
            if (ma.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Chọn một dòng để xóa!");
                return;
            }

            DBContext db = new DBContext();
            Connection conn = db.getConnection();
            // CHỈ XÓA ĐÚNG CÁI MÃ ĐANG CHỌN
            String sql = "DELETE FROM NHA_CUNG_CAP WHERE maNCC = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, ma);

            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đã xóa xong!");

            loadData(); // Cập nhật lại bảng (Dữ liệu khác vẫn còn nguyên)
            conn.close();
             clearForm(); //Thêm dòng này vào đây để xóa trắng các ô
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            // 1. Lấy dữ liệu từ các ô nhập
            String ma = txtMaNCC.getText();
            String ten = txtTenNCC.getText();
            String diachi = txtDiaChi.getText();
            String sdt = txtSDT.getText();
            String loai = cbLoaiHang.getSelectedItem().toString();

            DBContext db = new DBContext();
            Connection conn = db.getConnection();

            // 2. LỆNH SQL PHẢI LÀ UPDATE (SỬA) - KHÔNG PHẢI DELETE
            String sql = "UPDATE NHA_CUNG_CAP SET tenNCC=?, diaChi=?, soDT=?, loaiHang=? WHERE maNCC=?";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, ten);
            st.setString(2, diachi);
            st.setString(3, sdt);
            st.setString(4, loai);
            st.setString(5, ma); // Mã nằm ở cuối cùng để so khớp WHERE

            // 3. Thực hiện
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật (Sửa) thành công!"); // Nhớ sửa chữ ở đây

            loadData(); // Nạp lại bảng
            conn.close();
                clearForm(); //Thêm dòng này vào đây để xóa trắng các ô
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNCCMouseClicked
// 1. Lấy vị trí dòng mà Đạt vừa bấm chuột vào
int row = jTableNCC.getSelectedRow();

if (row >= 0) {
    // 1. Lấy mã Nhà cung cấp (Cột 0: maNCC) để hiển thị ảnh
    String maNCC = jTableNCC.getValueAt(row, 0).toString();
    
    // Đường dẫn ảnh NCC
    String path = "src/images_ncc/" + maNCC + ".jpg";
    
    // Gọi hàm hiển thị lên jLabel7
    updateImageNCC(path);
    
    // 2. Đổ dữ liệu từ bảng lên các ô nhập liệu (Sửa chỉ số cột tại đây)
    txtMaNCC.setText(jTableNCC.getValueAt(row, 0).toString());  // Cột 0: maNCC
    txtTenNCC.setText(jTableNCC.getValueAt(row, 1).toString()); // Cột 1: tenNCC

    // ĐỔI LẠI VỊ TRÍ CỘT 2 VÀ 3:
    // Cột 3 trên bảng là Địa chỉ (TP. Hồ Chí Minh, Bắc Ninh...)
    txtDiaChi.setText(jTableNCC.getValueAt(row, 2).toString());
    
    // Cột 2 trên bảng là Số điện thoại (0903..., 0983...)
    txtSDT.setText(jTableNCC.getValueAt(row, 3).toString());

    // Cột 4 là Loại hàng đưa vào ComboBox
    cbLoaiHang.setSelectedItem(jTableNCC.getValueAt(row, 4).toString());
}       // TODO add your handling code here:
    }//GEN-LAST:event_jTableNCCMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

        // 1. Mở lại trang chủ MainFrame
        MainFrame main = new MainFrame();
        main.setVisible(true);

        // 2. Tắt (giải phóng) cái cửa sổ Nhà Cung Cấp này đi
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaCungCapFrame().setVisible(true);
            }
        });
    }

    private void clearForm() {
    }

    public void updateImageNCC(String imagePath) {
        if (imagePath == null || imagePath.isEmpty()) {
            jLabel7.setIcon(null);
            jLabel7.setText("No Image");
            return;
        }
        try {
            ImageIcon myImage = new ImageIcon(imagePath);
            Image img = myImage.getImage();

            // Lấy kích thước của jLabel7 để scale ảnh
            int width = jLabel7.getWidth() > 0 ? jLabel7.getWidth() : 180;
            int height = jLabel7.getHeight() > 0 ? jLabel7.getHeight() : 180;

            Image newImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            jLabel7.setIcon(new ImageIcon(newImg));
            jLabel7.setText("");
        } catch (Exception e) {
            jLabel7.setIcon(null);
            System.out.println("Lỗi load ảnh NCC: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNCC;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
