
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class PheDuyetFrame extends javax.swing.JFrame {

    public void loadTable() {
        try {
            Connection conn = new DBContext().getConnection();
            // Sửa maPhieu thành maYC, tenVatLieu thành tenNVL theo đúng SQL của Đạt
            String sql = "SELECT maYC, tenNVL, soLuong, nguoiYeuCau FROM YEU_CAU WHERE trangThai = N'Đang chờ'";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblPheDuyet.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("maYC"), // Khớp với maYC trong SQL
                    rs.getString("tenNVL"), // Khớp với tenNVL
                    rs.getInt("soLuong"),
                    rs.getString("nguoiYeuCau")
                });
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form PheDuyetFrame
     */
    public PheDuyetFrame() {
        initComponents();
        loadTable(); // Phải có dòng này thì mở lên bảng mới có dữ liệu Đạt nhé!
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPheDuyet = new javax.swing.JTable();
        btnDuyet = new javax.swing.JButton();
        btnTuChoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("PHÊ DUYỆT YÊU CẦU VẬT TƯ");

        tblPheDuyet.setBackground(new java.awt.Color(255, 204, 204));
        tblPheDuyet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "Vật Liệu", "Số Lượng", "Người Yêu Cầu"
            }
        ));
        jScrollPane1.setViewportView(tblPheDuyet);

        btnDuyet.setBackground(new java.awt.Color(255, 255, 153));
        btnDuyet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDuyet.setText("Duyệt");
        btnDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyetActionPerformed(evt);
            }
        });

        btnTuChoi.setBackground(new java.awt.Color(255, 255, 102));
        btnTuChoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTuChoi.setText("Từ chối");
        btnTuChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuChoiActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(335, 335, 335))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)
                            .addComponent(btnTuChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(438, 438, 438)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTuChoi)
                    .addComponent(btnDuyet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetActionPerformed
        int row = tblPheDuyet.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một yêu cầu để phê duyệt!");
            return;
        }

        try {
            // 1. Lấy mã yêu cầu (maYC) và ép kiểu về Int
            int idYC = Integer.parseInt(tblPheDuyet.getValueAt(row, 0).toString().trim());

            Connection conn = new DBContext().getConnection();

            // 2. SQL theo đúng bảng YEU_CAU và cột maYC
            String sql = "UPDATE YEU_CAU SET trangThai = ? WHERE maYC = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            // 3. Sử dụng setNString để hỗ trợ tiếng Việt có dấu
            pstmt.setNString(1, "Đã duyệt");
            pstmt.setInt(2, idYC);

            int result = pstmt.executeUpdate();
            conn.close();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Đã phê duyệt thành công yêu cầu số: " + idYC);
                loadTable(); // Hàm này để tải lại dữ liệu lên bảng
            } else {
                System.out.println("Lỗi: Không tìm thấy maYC = " + idYC + " trong bảng YEU_CAU");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối hoặc thực thi: " + e.getMessage());
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDuyetActionPerformed

    private void btnTuChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuChoiActionPerformed
        int row = tblPheDuyet.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một yêu cầu để từ chối!");
            return;
        }

        try {
            int idYC = Integer.parseInt(tblPheDuyet.getValueAt(row, 0).toString().trim());
            Connection conn = new DBContext().getConnection();

            String sql = "UPDATE YEU_CAU SET trangThai = ? WHERE maYC = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setNString(1, "Từ chối");
            pstmt.setInt(2, idYC);

            int result = pstmt.executeUpdate();
            conn.close();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Đã từ chối yêu cầu số: " + idYC);
                loadTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTuChoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
// 1. Mở lại trang chủ VatLieuFrame
        VatLieuFrame main = new VatLieuFrame();
        main.setVisible(true);

        // 2. Tắt (giải phóng) cái cửa sổ Phe Duyet này đi
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PheDuyetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PheDuyetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PheDuyetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PheDuyetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PheDuyetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuyet;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTuChoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPheDuyet;
    // End of variables declaration//GEN-END:variables
}
