
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import java.awt.Image;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class VatLieuFrame extends javax.swing.JFrame {

    DefaultTableModel model;

    public void loadDataToTable() {
        model = (DefaultTableModel) tblVatLieu.getModel();
        model.setRowCount(0);
        try {
            // Sử dụng DBContext của bạn
            Connection conn = new DBContext().getConnection();
            String sql = "SELECT * FROM NGUYEN_VAT_LIEU";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maNVL"),
                    rs.getString("tenNVL"),
                    rs.getString("loaiNVL"),
                    rs.getInt("soLuong"),
                    rs.getFloat("donGia")
                });
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp dữ liệu: " + e.getMessage());
        }
    }

    /**
     * Creates new form VatLieuFrame
     */
    public VatLieuFrame() {
        initComponents();
        model = (DefaultTableModel) tblVatLieu.getModel();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVatLieu = new javax.swing.JTable();
        cboLocLoai = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soLuong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboLoaiNVL = new javax.swing.JComboBox<>();
        txtMaNVL = new javax.swing.JTextField();
        txtTenNVL = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtdonGia = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnYeuCau = new javax.swing.JButton();
        btnPheDuyet = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("NGUYÊN VẬT LIỆU ");

        tblVatLieu.setBackground(new java.awt.Color(204, 255, 255));
        tblVatLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "maNVL", "tenNVL", "loaiNVL", "soLuong", "donGia"
            }
        ));
        tblVatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVatLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVatLieu);

        cboLocLoai.setBackground(new java.awt.Color(204, 255, 204));
        cboLocLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboLocLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Phần cứng", "Phần mềm" }));
        cboLocLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocLoaiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("maNVL");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("tenNVL");

        soLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuong.setText("soLuong");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("donGia");

        cboLoaiNVL.setBackground(new java.awt.Color(204, 255, 204));
        cboLoaiNVL.setEditable(true);
        cboLoaiNVL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboLoaiNVL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phần cứng", "Phần mềm" }));

        txtMaNVL.setBackground(new java.awt.Color(204, 255, 204));
        txtMaNVL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTenNVL.setBackground(new java.awt.Color(204, 255, 204));
        txtTenNVL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSoLuong.setBackground(new java.awt.Color(204, 255, 204));
        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        txtdonGia.setBackground(new java.awt.Color(204, 255, 204));
        txtdonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSua.setBackground(new java.awt.Color(204, 255, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 255, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 255, 204));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnYeuCau.setBackground(new java.awt.Color(204, 255, 204));
        btnYeuCau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnYeuCau.setText("Yêu cầu");
        btnYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeuCauActionPerformed(evt);
            }
        });

        btnPheDuyet.setBackground(new java.awt.Color(204, 255, 204));
        btnPheDuyet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPheDuyet.setText("Phê duyệt");
        btnPheDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPheDuyetActionPerformed(evt);
            }
        });

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnThoat)))
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboLoaiNVL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMaNVL, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtTenNVL))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtdonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(txtSoLuong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnYeuCau)
                    .addComponent(btnSua))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addComponent(btnPheDuyet))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMaNVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cboLoaiNVL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(soLuong))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPheDuyet)
                            .addComponent(btnYeuCau))
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat)))
                .addGap(36, 36, 36))
        );

        txtTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboLocLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboLocLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 216, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        try {
            // 1. Phải đảm bảo model đã được khởi tạo (Sửa lỗi Null)
            if (model == null) {
                model = (DefaultTableModel) tblVatLieu.getModel();
            }

            // 2. Kết nối CSDL từ DBContext của bạn
            Connection conn = new DBContext().getConnection();

            // 3. Câu lệnh SQL Insert chuẩn theo bảng NGUYEN_VAT_LIEU
            String sql = "INSERT INTO NGUYEN_VAT_LIEU (maNVL, tenNVL, loaiNVL, soLuong, donGia) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            // 4. Lấy dữ liệu từ các ô nhập liệu
            pstmt.setString(1, txtMaNVL.getText());
            pstmt.setString(2, txtTenNVL.getText());
            pstmt.setString(3, cboLoaiNVL.getSelectedItem().toString());
            pstmt.setInt(4, Integer.parseInt(txtSoLuong.getText()));
            pstmt.setFloat(5, Float.parseFloat(txtdonGia.getText()));

            // 5. Thực thi và nạp lại bảng
            pstmt.executeUpdate();
            conn.close();

            loadDataToTable(); // Gọi hàm này để cập nhật bảng màu Cyan
            clearForm();       // THÊM DÒNG NÀY Ở ĐÂY để xóa trắng các ô nhập liệu
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Số lượng và Đơn giá phải là số!");
        } catch (Exception e) {
            // Bắt lỗi trùng khóa chính (HW10...)
            if (e.getMessage().contains("PRIMARY KEY")) {
                JOptionPane.showMessageDialog(this, "Mã này đã tồn tại, vui lòng nhập mã khác!");
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            }

        }     // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            // 1. Kết nối DB
            Connection conn = new DBContext().getConnection();

            // 2. Lấy mã NVL từ ô nhập liệu để biết xóa dòng nào
            String ma = txtMaNVL.getText();

            // Kiểm tra xem người dùng đã nhập/chọn mã chưa
            if (ma.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc nhập mã NVL cần xóa!");
                return;
            }

            // 3. Hỏi xác nhận trước khi xóa cho chắc ăn
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa nguyên vật liệu này?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM NGUYEN_VAT_LIEU WHERE maNVL = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, ma);

                pstmt.executeUpdate();

                // 4. Cập nhật lại bảng và xóa trắng form
                loadDataToTable();
                txtMaNVL.setText("");
                txtTenNVL.setText("");
                txtSoLuong.setText("");
                txtdonGia.setText("");

                JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
            }
            conn.close();
 clearForm(); //Thêm dòng này vào đây để xóa trắng các ô
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblVatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVatLieuMouseClicked
        int row = tblVatLieu.getSelectedRow();
        if (row >= 0) {
    
    // 2. Lấy mã NVL ở cột 0 (để dùng làm tên file ảnh)
    String maNVL = tblVatLieu.getValueAt(row, 0).toString();
    
    // 3. Đường dẫn file (Bạn sửa lại cho đúng thư mục chứa ảnh của bạn nhé)
    String path = "src/images/" + maNVL + ".jpg"; 
    
    // 4. GỌI HÀM ĐÃ VIẾT Ở BƯỚC 1
    updateImage(path);
    
    // (Các code hiển thị maNVL, tenNVL... lên TextField giữ nguyên)
            // Lấy mã vật liệu để làm tên file ảnh
        String ma = tblVatLieu.getValueAt(row, 0).toString();
        
        // Gọi hàm hiển thị ảnh (nhớ kiểm tra đúng tên thư mục chứa ảnh của bạn)
        updateImage("src/images/" + ma + ".jpg");
            // Cách này an toàn hơn: Lấy giá trị ra rồi cộng với chuỗi rỗng
            // Nếu ô đó bị null, nó sẽ biến thành chuỗi rỗng thay vì báo lỗi
            txtMaNVL.setText(tblVatLieu.getValueAt(row, 0) + "");
            txtTenNVL.setText(tblVatLieu.getValueAt(row, 1) + "");
            cboLoaiNVL.setSelectedItem(tblVatLieu.getValueAt(row, 2) + "");
            txtSoLuong.setText(tblVatLieu.getValueAt(row, 3) + "");
            txtdonGia.setText(tblVatLieu.getValueAt(row, 4) + "");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_tblVatLieuMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            // 1. Kết nối đến CSDL từ file DBContext của Đạt
            Connection conn = new DBContext().getConnection();

            // 2. Câu lệnh SQL Update dựa trên mã NVL
            String sql = "UPDATE NGUYEN_VAT_LIEU SET tenNVL=?, loaiNVL=?, soLuong=?, donGia=? WHERE maNVL=?";

            PreparedStatement pstmt = conn.prepareStatement(sql);

            // 3. Truyền dữ liệu từ các ô nhập liệu vào câu lệnh
            pstmt.setString(1, txtTenNVL.getText());
            pstmt.setString(2, cboLoaiNVL.getSelectedItem().toString());
            pstmt.setInt(3, Integer.parseInt(txtSoLuong.getText()));
            pstmt.setFloat(4, Float.parseFloat(txtdonGia.getText()));
            pstmt.setString(5, txtMaNVL.getText()); // Điều kiện WHERE dùng maNVL

            // 4. Thực thi cập nhật
            int rows = pstmt.executeUpdate();
            conn.close();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");
                loadDataToTable(); // Nạp lại bảng màu xanh để thấy thay đổi
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã NVL để sửa!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cboLocLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocLoaiActionPerformed
        String loaiChon = cboLocLoai.getSelectedItem().toString(); // Kiểm tra xem tên có đúng là jComboBox1 không
        filterByLoai(loaiChon);        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocLoaiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            // 1. Lấy nội dung cần tìm (xóa khoảng trắng thừa)
            String input = txtTimKiem.getText().trim();

            // 2. Kết nối CSDL
            Connection conn = new DBContext().getConnection();

            // 3. Câu lệnh SQL tìm kiếm theo Mã hoặc Tên (dùng LIKE để tìm gần đúng)
            // Dấu N'?' dùng để hỗ trợ tìm tiếng Việt có dấu
            String sql = "SELECT * FROM NGUYEN_VAT_LIEU WHERE maNVL LIKE ? OR tenNVL LIKE ?";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, "%" + input + "%"); // % giúp tìm chữ nằm ở bất kỳ đâu
            pstmt.setString(2, "%" + input + "%");

            ResultSet rs = pstmt.executeQuery();

            // 4. Xóa bảng cũ và nạp kết quả tìm thấy vào bảng màu xanh
            model = (DefaultTableModel) tblVatLieu.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maNVL"),
                    rs.getString("tenNVL"),
                    rs.getString("loaiNVL"),
                    rs.getInt("soLuong"),
                    rs.getFloat("donGia")
                });
            }

            conn.close();

            // Nếu không tìm thấy gì thì báo nhẹ một câu
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nguyên vật liệu nào khớp!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
// 1. Khởi tạo lại màn hình chính (MainFrame)
        // Lưu ý: Đạt kiểm tra chính xác tên Class của màn hình trong ảnh là gì nhé
        MainFrame main = new MainFrame();

        // 2. Hiển thị màn hình chính lên
        main.setVisible(true);
        main.setLocationRelativeTo(null); // Để nó hiện giữa màn hình

        // 3. Đóng (giải phóng) cửa sổ hiện tại (VatLieuFrame)
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeuCauActionPerformed
                                            
    // 1. Khởi tạo đối tượng của trang yêu cầu
    YeuCauFrame pd = new YeuCauFrame();
    
    // 2. Hiển thị trang đó lên
    pd.setVisible(true);
    
    // 3. Đưa trang đó ra chính giữa màn hình cho đẹp
    pd.setLocationRelativeTo(null);
    
    // 4. (Tùy chọn) Nếu Đạt muốn đóng trang Nguyên vật liệu hiện tại thì thêm dòng này:
    // this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYeuCauActionPerformed

    private void btnPheDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPheDuyetActionPerformed
// 1. Khởi tạo đối tượng của trang Phê duyệt
    PheDuyetFrame pd = new PheDuyetFrame();
    
    // 2. Hiển thị trang đó lên
    pd.setVisible(true);
    
    // 3. Đưa trang đó ra chính giữa màn hình cho đẹp
    pd.setLocationRelativeTo(null);
    
    // 4. (Tùy chọn) Nếu Đạt muốn đóng trang Nguyên vật liệu hiện tại thì thêm dòng này:
    // this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPheDuyetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VatLieuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VatLieuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VatLieuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VatLieuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VatLieuFrame().setVisible(true);
            }
        });
    }

    private void clearForm() {
        txtMaNVL.setText("");
        txtTenNVL.setText("");
        txtSoLuong.setText("");
        txtdonGia.setText("");
        cboLoaiNVL.setSelectedIndex(0); // Quay về lựa chọn đầu tiên
        txtMaNVL.requestFocus(); // Đưa con trỏ chuột về ô Mã để nhập tiếp luôn
    }

    public void filterByLoai(String loai) {
        model = (DefaultTableModel) tblVatLieu.getModel();
        model.setRowCount(0);
        try {
            Connection conn = new DBContext().getConnection();
            String sql;
            if (loai.equals("Tất cả")) {
                sql = "SELECT * FROM NGUYEN_VAT_LIEU";
            } else {
                sql = "SELECT * FROM NGUYEN_VAT_LIEU WHERE loaiNVL = ?";
            }

            PreparedStatement pstmt = conn.prepareStatement(sql);
            if (!loai.equals("Tất cả")) {
                pstmt.setString(1, loai);
            }

            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("maNVL"), rs.getString("tenNVL"),
                    rs.getString("loaiNVL"), rs.getInt("soLuong"), rs.getFloat("donGia")
                });
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   public void updateImage(String imagePath) {
    if (imagePath == null || imagePath.isEmpty()) {
        jLabel4.setIcon(null);
        jLabel4.setText("No Image");
        return;
    }
    
    ImageIcon myImage = new ImageIcon(imagePath);
    Image img = myImage.getImage();
    
    // Lấy kích thước của jLabel4. 
    // Nếu getWidth = 0 (do giao diện chưa load xong), ta đặt mặc định khoảng 150-200
    int width = jLabel4.getWidth() > 0 ? jLabel4.getWidth() : 180;
    int height = jLabel4.getHeight() > 0 ? jLabel4.getHeight() : 180;

    // ÉP ẢNH VỀ ĐÚNG KÍCH THƯỚC KHUNG
    Image newImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
    
    jLabel4.setIcon(new ImageIcon(newImg));
    jLabel4.setText(""); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPheDuyet;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnYeuCau;
    private javax.swing.JComboBox<String> cboLoaiNVL;
    private javax.swing.JComboBox<String> cboLocLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel soLuong;
    private javax.swing.JTable tblVatLieu;
    private javax.swing.JTextField txtMaNVL;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenNVL;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtdonGia;
    // End of variables declaration//GEN-END:variables
}
